services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception-net
    volumes:
      - /home/yoda/data/wp:/var/www/html

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception-net
    volumes:
      - /home/yoda/data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    networks:
      - inception-net
    volumes:
      - /home/yoda/data/wp:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN: ${WORDPRESS_ADMIN}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
    depends_on:
      - mariadb

networks:
  inception-net:
    driver: bridge
    name: inception-net