services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8443:443"
    restart: always
    # depends_on:
    #   - app
    networks:
      - frontend
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: yoda
      MYSQL_PASSWORD: yoda

networks:
  frontend:
  backend:

volumes:
  mariadb: